import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/app/providers";
import clsx from "clsx";
import { Header } from "@/shared/components/core/header";
import { Navigation } from "@/shared/components/core/navigation";
import Script from "next/script";
import { TmaSDKLoader } from "@/shared/components/TmaSDKLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={clsx(
					inter.className,
					"bg-colors-telegram-background",
					"min-h-screen"
				)}
			>
				<TmaSDKLoader>
					<Script
						src="https://telegram.org/js/telegram-web-app.js"
						strategy={"afterInteractive"}
					/>
					<Providers>
						<div className={"flex flex-col gap-4"}>
							<Header />
							{children}
						</div>
						<Navigation />
					</Providers>
				</TmaSDKLoader>
			</body>
		</html>
	);
}
